extensions:
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: true
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  filesytem:
    args:
    - -y
    - '@modelcontextprotocol/server-filesystem'
    - /home/lio/g
    bundled: null
    cmd: npx
    description: 'access files inside ~/g '
    enabled: true
    env_keys: []
    envs: {}
    name: filesytem
    timeout: 300
    type: stdio
  filesytem-extension:
    args:
    - -y
    - '@modelcontextprotocol/server-filesystem'
    bundled: null
    cmd: npx
    description: null
    enabled: false
    env_keys: []
    envs: {}
    name: filesytem-extension
    timeout: 300
    type: stdio
  memory:
    bundled: true
    display_name: Memory
    enabled: true
    name: memory
    timeout: 300
    type: builtin
